// ProjectData.jsx — All project information

const PROJECTS = {
  mylokai: {
    title: 'MyLokAI',
    tagline: 'Privacy-first on-device AI chat',
    description: 'Most AI chat apps ship your data to the cloud. MyLokAI runs entirely on your device — no accounts, no network calls for inference, no one else seeing your conversations.',
    status: 'Shipped',
    platform: 'iOS',
    year: '2025',
    category: 'shipped',
    color: 'oklch(0.70 0.12 170)',
    tech: ['Swift 6', 'SwiftUI', 'Apple Foundation Models', 'MLX Swift', 'SwiftData'],
    story: 'Built to prove the privacy-first thesis in a consumer app. Device-aware model tiering (4B on 8GB devices, up to 7B on 12GB) means the experience degrades gracefully instead of crashing. Apple Foundation Models is the default so new users never wait for a download.',
    links: { appstore: 'https://apps.apple.com/us/app/mylokai/id6760079666' },
    features: [
      'Fully on-device inference — no cloud, no accounts',
      'Device-aware model tiering across Apple Silicon',
      'Curated Hugging Face model catalog',
      'Warm minimal design inspired by Things 3',
    ],
  },
  orttaai: {
    title: 'orttaai',
    tagline: 'Offline speech-to-text, no subscription',
    description: 'A local voice keyboard for macOS, Linux, and Windows. It runs speech recognition on-device and injects text into whatever app has focus — no cloud and no subscription.',
    status: 'Shipped',
    platform: 'macOS / Linux / Windows',
    year: '2025',
    category: 'shipped',
    color: 'oklch(0.55 0.14 280)',
    tech: ['Swift', 'SwiftUI', 'WhisperKit', 'Rust', 'Tauri'],
    story: 'Wispr Flow charges monthly for something your machine can do locally. orttaai runs speech recognition on your hardware and injects text directly into whatever app has focus. The native macOS app uses WhisperKit, while the Rust and Tauri desktop edition brings the same workflow to Linux and Windows.',
    links: {
      github: 'https://github.com/theoyinbooke/orttaai',
      downloads: 'https://github.com/theoyinbooke/orttaai-desktop/releases/latest',
    },
    features: [
      'Local speech recognition with zero cloud dependency',
      'Push-to-talk dictation with spoken line-break commands',
      'Fast, complete dictation from one authoritative recording and finalized transcript',
      'Clipboard-safe delivery that preserves newer Universal Clipboard content',
      'Codex and Grok CLI integrations with explicit cloud-text consent',
      'Selectable model storage on external drives with compatible-model reuse',
      'Quantized Whisper models with downloads up to 5x smaller',
      'Installable releases for macOS, Linux, and Windows',
    ],
  },
  reelmify: {
    title: 'Reelmify',
    tagline: 'Private Mac studio for social video',
    description: 'A native Mac studio for turning long-form footage and short social videos into polished vertical content with local transcription, editing, captions, and export.',
    status: 'Shipped',
    platform: 'macOS',
    year: '2026',
    category: 'shipped',
    color: 'oklch(0.64 0.16 35)',
    tech: ['Swift', 'SwiftUI', 'AVFoundation', 'WhisperKit', 'Sparkle'],
    story: 'Most social-video workflows start by uploading source footage to a cloud service. Reelmify keeps source files, projects, edits, and transcription on the Mac while providing focused workflows for generating clips from long-form video or directly editing short portrait content.',
    links: { website: 'https://reelmify.theoyinbooke.com/' },
    features: [
      'Editable transcripts that preserve caption timing and keyword highlights',
      'Subject-aware portrait reframing for landscape and multi-speaker footage',
      'Quality-gated two-, three-, and five-part connected series',
      'Unified link imports with persistent, resumable background jobs',
      'Link previews with metadata, quality choices, and multi-video selection before downloads',
      'Configurable data storage on the Mac or an external drive',
      'Codex and Grok CLI narrative planning with custom executable selection',
      'CLI, MCP, and companion API for agent-controlled workflows',
      'iPhone companion for project search, source playback, and variation previews while processing stays on the Mac',
    ],
  },
  thynkora: {
    title: 'Thynkora',
    tagline: 'Daily imagination training with AI feedback',
    description: 'A native iPhone app for strengthening imagination as a measurable skill through short creative challenges, fast AI scoring, and progress tracking across visual, narrative, conceptual, and empathic thinking.',
    status: 'In Development',
    platform: 'iPhone',
    year: '2026',
    category: 'building',
    color: 'oklch(0.63 0.16 305)',
    tech: ['SwiftUI', 'SwiftData', 'CloudKit', 'Sign in with Apple', 'AI scoring'],
    story: 'Thynkora treats imagination like a skill you can practice. Users complete daily creative prompts, receive structured feedback, and build an imagination profile across multiple dimensions instead of relying on vague inspiration or one-off journaling.',
    links: {},
    features: [
      'Daily creative challenges across four imagination dimensions',
      'AI-scored feedback for originality, depth, and quality',
      'Progress tracking and imagination profile over time',
      'Private sign-in and lightweight iPhone-first experience',
    ],
  },
  kulosar: {
    title: 'KulosAr',
    tagline: 'AI companion for meaningful relationships',
    description: 'A mobile app for nurturing meaningful connections through voice and text journaling, relationship insights, personalized messages, and daily briefings that help users stay present with the people who matter most.',
    status: 'In Development',
    platform: 'iPhone / iPad / Android',
    year: '2026',
    category: 'building',
    color: 'oklch(0.68 0.15 25)',
    tech: ['iOS', 'Voice journaling', 'AI insights', 'Personalized messaging', 'Daily briefings'],
    story: 'KulosAr is built around the quiet work of staying close to people. Users can capture thoughts by voice or text, then use AI-generated insights, message drafts in their own voice, and daily relationship briefings to turn reflection into intentional connection.',
    links: {},
    features: [
      'Voice and text journaling for relationship context',
      'AI-generated insights about meaningful connections',
      'Personalized message drafts in the user\'s own voice',
      'Daily briefings that encourage presence and follow-through',
    ],
  },
  meetumo: {
    title: 'MeetUmo',
    tagline: 'Event platform for tickets, engagement, and sponsor ROI',
    description: 'Create and run high-impact events from one platform: ticketing, attendee engagement, QR check-in, analytics, certificates, and sponsor ROI reporting.',
    status: 'Shipped',
    platform: 'Web / iPhone / iPad',
    year: '2026',
    category: 'shipped',
    color: 'oklch(0.67 0.13 185)',
    tech: ['Next.js', 'React', 'Clerk', 'Event analytics', 'QR check-in'],
    story: 'Event organizers should not have to stitch together ticketing, check-in, attendee engagement, certificates, and sponsor reporting across separate tools. MeetUmo brings the full event workflow into one platform, with companion mobile access and analytics that help organizers prove value after the event.',
    links: {
      website: 'https://meetumo.ai',
      appstore: 'https://apps.apple.com/us/app/meetumo/id6756896813',
    },
    features: [
      'Event ticketing and registration',
      'Attendee engagement, networking, and Bluetooth Nearby Mode',
      'QR code check-in for event operations',
      'Sponsor, exhibitor, and ROI reporting',
    ],
  },
  wegosign: {
    title: 'WeGoSign',
    tagline: 'Document signing for African businesses',
    description: 'Send documents for signature, track progress, and close contracts faster without printing, dispatch riders, or chasing signatures manually.',
    status: 'Shipped',
    platform: 'Web / API',
    year: '2026',
    category: 'shipped',
    color: 'oklch(0.62 0.18 145)',
    tech: ['Next.js', 'React', 'Clerk', 'Document APIs', 'E-signatures'],
    story: 'Paperwork slows down deals, especially when signing still depends on printing, courier runs, and manual follow-up. WeGoSign gives businesses a fast, browser-based signing workflow with legally valid documents, audit trails, reusable templates, and a developer-friendly API.',
    links: { website: 'https://wegosign.com' },
    features: [
      'Browser-based signing with no app download for recipients',
      'Reusable templates for common contracts and agreements',
      'Automatic reminders and instant signed copies',
      'Audit trails for every document',
    ],
  },
  eimailar: {
    title: 'eimailar',
    tagline: 'Self-hosted email infrastructure for products',
    description: 'An API-first email platform for transactional delivery and marketing campaigns, with one operating surface for sending domains, audiences, delivery events, and reputation safeguards.',
    status: 'In Development',
    platform: 'Web / API',
    year: '2026',
    category: 'building',
    color: 'oklch(0.66 0.17 50)',
    tech: ['Next.js', 'Fastify', 'PostgreSQL', 'Redis', 'AWS SES'],
    story: 'Product email usually splits into one system for transactional messages, another for campaigns, and a pile of glue for contacts, webhooks, and delivery health. eimailar brings that work into a self-hosted stack with an API-first sending layer and an operations-focused dashboard.',
    links: { website: 'https://app.eimailar.com/' },
    features: [
      'Hosted and embeddable subscriber forms with custom questions',
      'API keys, verified sending domains, and delivery webhooks',
      'Visual email studio with branded starters and personalization',
      'Bounce and complaint suppression with reputation guardrails',
    ],
  },
  learnwhilebuilding: {
    title: 'Learn While Building',
    tagline: 'Learning layer for building with coding agents',
    description: 'A learning layer for people building real software with coding agents. It turns project decisions into clear mental models, useful practice, and knowledge that returns when you need it.',
    status: 'Shipped',
    platform: 'Web / Codex Plugin',
    year: '2026',
    category: 'shipped',
    color: 'oklch(0.53 0.10 125)',
    tech: ['Python', 'Codex Plugin', 'HTML', 'Behavioral evals'],
    story: 'Learn While Building sits alongside the build instead of replacing it with a course. It uses the active request, project evidence, tests, and the learner\'s objective to keep the software outcome first while making important decisions teachable through bounded briefs, learning diffs, practice, recall, and explicit privacy choices.',
    links: {
      website: 'https://theoyinbooke.github.io/learn-while-building/',
      github: 'https://github.com/theoyinbooke/learn-while-building',
    },
    features: [
      'Bounded 30-second learning brief before normal task detail',
      'Quiet, Coach, and Deep modes with gradual handback',
      'Project-grounded Learning Diffs with practice and delayed recall',
      'Session-only, private-project, and shared-project learning state',
    ],
  },
  iquipar: {
    title: 'iquipAr',
    tagline: 'Citation-first civic knowledge for Nigeria',
    description: 'A grounded guide to how Nigeria\'s government works: constitutional structure, legislative powers, public processes, money, a multi-track timeline, and an advisory engine that answers with primary-source citations.',
    status: 'In Development',
    platform: 'Web',
    year: '2026',
    category: 'building',
    color: 'oklch(0.58 0.14 220)',
    tech: ['Next.js', 'TypeScript', 'Supabase', 'PostgreSQL', 'pgvector'],
    story: 'iquipAr turns Nigerian government knowledge into something you can explore and question. It connects an eight-module learning path, a Nigeria explorer, process labs, and a citation-first advisory workspace so answers can be checked against primary sources instead of trusting model prose alone.',
    links: { website: 'https://iquipar.ng/' },
    features: [
      'Eight-module path from the Constitution to cited Q&A',
      'Interactive Nigeria map and process lab',
      'Multi-track timeline across constitutional, governmental, political, economic, and social history',
      'Advisory answers with primary-source citations and explicit refusal when evidence is insufficient',
    ],
  },
  pewpad: {
    title: 'PewPad',
    tagline: 'Private preaching memory for pastors',
    description: 'An on-device preaching companion for pastors to prepare, deliver, and multiply sermons in their own voice — with the sermon archive kept private on iPhone and iPad.',
    status: 'Shipped',
    platform: 'iPhone / iPad',
    year: '2026',
    category: 'shipped',
    color: 'oklch(0.66 0.13 115)',
    tech: ['SwiftUI', 'SwiftData', 'CloudKit', 'SpeechAnalyzer', 'Apple Foundation Models', 'MLX Swift'],
    story: 'Pewpad is built around the preacher\'s week: prepared in the study, delivered from the pulpit, multiplied through follow-up, and remembered across years. It treats each sermon as structured data, keeps Bible references and commentary close to the manuscript, listens privately in Pulpit Mode for spoken references, and uses on-device intelligence to surface archive memory and generate ministry materials without uploading the pastor\'s sermons.',
    links: {
      website: 'https://pewpad.ai',
      appstore: 'https://apps.apple.com/us/app/pewpad/id6766775466',
    },
    features: [
      'Pulpit Mode with manuscript and scripture side by side',
      'Voice-triggered Bible reference loading during delivery',
      'Private sermon memory graph for themes, scripture, and illustrations',
      'Ministry Kit outputs: recap email, discussion guide, and devotional',
    ],
  },
  yaypeng: {
    title: 'YayPeng',
    tagline: 'iPad-native photo booth for events',
    description: 'A clean photo booth app for event operators to capture guest photos, compose branded photo strips, and deliver finished images by email link without bloated subscription tooling.',
    status: 'In Development',
    platform: 'iPad',
    year: '2026',
    category: 'building',
    color: 'oklch(0.72 0.15 85)',
    tech: ['SwiftUI', 'AVFoundation', 'Convex', 'Clerk', 'Resend'],
    story: 'YayPeng is built for the operator standing beside the booth: set up an event, pick a template, customize the strip, capture with the built-in or external camera, and send guests a share link without fighting a maze of settings.',
    links: {},
    features: [
      'iPad photo booth capture with built-in or external cameras',
      'Branded strip templates for weddings, parties, and events',
      'Guest delivery through email share links',
      'Simple event-operator workflow without bloated settings',
    ],
  },
  gopakd: {
    title: 'GoPakd',
    tagline: 'Group trip planning for real life',
    description: 'Trip planning and coordination for families, couples, and friend groups — with dual on-device + cloud AI. One shared workspace for packing, itineraries, meals, and calendar coordination.',
    status: 'In Development',
    platform: 'iOS',
    year: '2026',
    category: 'building',
    color: 'oklch(0.60 0.15 60)',
    tech: ['SwiftUI', 'Convex', 'Clerk', 'Vercel AI SDK', 'Claude/GPT/Gemini', 'EventKit'],
    story: 'Group trip planning lives across group texts, shared docs, and someone\'s notes app. GoPakd is one shared workspace that coordinates packing lists, itineraries, meals, and calendars — with AI that actually understands the chaos of planning with other people.',
    links: {},
    features: [
      'Shared packing lists with smart suggestions',
      'Itinerary builder with calendar sync',
      'Dual AI: on-device for privacy, cloud for power',
      'Real-time collaboration via Convex',
    ],
  },
  apotiowomi: {
    title: 'Apotiowo Mi',
    tagline: 'Private budgeting with fast list-style logging',
    description: 'A native iPhone and iPad budgeting app for planning monthly budgets, splitting categories into practical line items, and logging income or spending from simple typed lists.',
    status: 'Shipped',
    platform: 'iPhone / iPad',
    year: '2026',
    category: 'shipped',
    color: 'oklch(0.64 0.14 315)',
    tech: ['SwiftUI', 'SwiftData', 'CloudKit', 'Sign in with Apple', 'VisionKit', 'Charts'],
    story: 'Apotiowo Mi is built for people who want budget tracking without turning their financial life into admin work. Users plan a budget by category, add line items under each category, and then log transactions by typing spending or income like a quick list. The app reviews parsed entries before anything is saved, keeps data on-device, and syncs only through the user\'s private iCloud when available.',
    links: {
      website: 'https://apotiowomi.vercel.app/',
      appstore: 'https://apps.apple.com/us/app/apotiowo-mi/id6774993384',
    },
    features: [
      'Monthly budgets with category and item-level planning',
      'Fast typed-list entry for income and expenses',
      'Review step before parsed transactions are saved',
      'On-device receipt scanning and private iCloud sync',
    ],
  },
  soundar: {
    title: 'soundAr',
    tagline: 'Local speech, music, and video studio',
    description: 'An open-source Linux desktop studio for local speech, music, and video production, with voice generation, comparison, and benchmarking.',
    status: 'Shipped',
    platform: 'Linux',
    year: '2026',
    category: 'shipped',
    color: 'oklch(0.55 0.12 250)',
    tech: ['React', 'Vite', 'Tauri', 'Python', 'PyTorch', 'CUDA'],
    story: 'soundAr puts local speech models behind a proper desktop workflow. Its Tauri app uses isolated Python workers and managed runtimes for generation, transcription, voice comparison, and benchmarking, while model weights and generated audio stay on the machine.',
    links: {
      github: 'https://github.com/theoyinbooke/soundAr',
      downloads: 'https://github.com/theoyinbooke/soundAr/releases/latest',
    },
    features: [
      'Local voice generation and cloning with open-source speech models',
      'Linux Video Studio with local media workflows, captions, timelines, and portrait export',
      'Integrated chat assistant with inline plans, activity, and generated media',
      'Side-by-side model comparison and GPU benchmark suite',
      'Durable batch jobs with pause, resume, retry, and cancellation',
      'Managed Linux runtime with explicit model downloads',
      'Pinned model installs and checksummed generated-audio history',
    ],
  },
  basicarly: {
    title: 'BasicArly',
    tagline: 'Learn transformers from first principles',
    description: 'A web learning platform that teaches how transformer models work through 30 structured modules, interactive visual explanations, quizzes, teach-backs, and hands-on building.',
    status: 'Shipped',
    platform: 'Web',
    year: '2026',
    category: 'shipped',
    color: 'oklch(0.60 0.16 285)',
    tech: ['Next.js', 'React', 'TypeScript', 'Convex', 'Three.js', 'Python'],
    story: 'BasicArly is for builders who want more than surface-level explanations of language models. The curriculum moves from tokens and embeddings through attention, training, inference, and a capstone, pairing plain-language stories with the technical ideas and opportunities to explain and build them yourself.',
    links: { website: 'https://basicarly.theoyinbooke.com/' },
    features: [
      'Thirty-module curriculum from language modeling to capstone',
      'Interactive visual explanations for attention and transformer concepts',
      'Quizzes, misconception checks, and teach-back exercises',
      'Progress tracking with a companion mobile learning experience',
    ],
  },
  saffev: {
    title: 'Saffev',
    tagline: 'Private observability for local AI',
    description: 'An open-source local AI black box that records model traffic and coding-agent sessions, detects sensitive data, and preserves searchable, tamper-evident history without sending it off-device.',
    status: 'Shipped',
    platform: 'macOS / Linux / Windows',
    year: '2026',
    category: 'shipped',
    color: 'oklch(0.62 0.13 155)',
    tech: ['Rust', 'Local LLMs', 'Ollama', 'LM Studio', 'SQLCipher'],
    story: 'AI tools keep fragmented histories and delete them on their own schedules. Saffev unifies local model traffic and coding-agent sessions into one searchable timeline, protects sensitive data before it reaches a model, and preserves an encrypted record with tamper-evident evidence.',
    links: {
      github: 'https://github.com/theoyinbooke/Saffev',
      downloads: 'https://github.com/theoyinbooke/Saffev/releases/latest',
    },
    features: [
      'Unified searchable timeline for model calls and coding-agent sessions',
      'On-device privacy report with opt-in masking and blocking',
      'Encrypted, tamper-evident history with verifiable audit bundles',
      'macOS menu-bar panel for overview, preservation, privacy, spend, and alerts',
      'Installable releases for macOS, Linux, and Windows',
    ],
  },
};

const FEATURED_PROJECTS = ['mylokai', 'orttaai', 'thynkora'];

const CATEGORIES = {
  shipped: { label: 'Shipped', description: 'Live products you can use today' },
  building: { label: 'Building', description: 'Active development, shipping soon' },
};

Object.assign(window, { PROJECTS, FEATURED_PROJECTS, CATEGORIES });
